version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-server
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3306:3306'
  phpmyadmin:
    container_name: myadmin
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
  react-web:
    container_name: react-frontend
    image: react-web
    ports: 
      - 5173:5173
  express-server:
    container_name: express-backend
    depends_on:
      - db
    image: express-mysql
    ports:
      - 3333:3333
volumes:
  db_data:
